/**
 * Global Widget Registry for Checks Direct OS
 * Each entry defines a widget type, its metadata, default config, and size options.
 */

export const WIDGET_SIZES = {
  small: { label: "Small", cols: 1, description: "1 column" },
  medium: { label: "Medium", cols: 2, description: "2 columns" },
  large: { label: "Large", cols: 3, description: "3 columns" },
  full: { label: "Full Width", cols: 12, description: "Full width" },
};

export const LAYOUT_OPTIONS = [
  { key: "single", label: "Single Column", description: "All widgets stacked in one column" },
  { key: "two", label: "Two Columns", description: "Two equal columns side by side" },
  { key: "three", label: "Three Columns", description: "Three equal columns" },
  { key: "dashboard", label: "Dashboard Grid", description: "Flexible grid with variable widget sizes" },
  { key: "hero_grid", label: "Hero + Grid", description: "Full-width hero with grid below" },
  { key: "sidebar", label: "Sidebar Layout", description: "Main content with right sidebar" },
];

// Category groupings for widget selector UI
export const WIDGET_CATEGORIES = {
  core: { label: "Core", colour: "#06b6d4" },
  learning: { label: "Learning", colour: "#8b5cf6" },
  sales: { label: "Sales", colour: "#ec2ca3" },
  compliance: { label: "Compliance", colour: "#f59e0b" },
  operations: { label: "Operations", colour: "#10b981" },
  ai: { label: "AI", colour: "#0ea5e9" },
};

// Master widget registry — every widget type available in the system
export const WIDGET_REGISTRY = {
  // ── CORE ──────────────────────────────────────────────────────────
  calendar: {
    type: "calendar",
    label: "Calendar",
    description: "Show upcoming events from the team calendar",
    category: "core",
    icon: "Calendar",
    defaultSize: "medium",
    defaultConfig: { maxEvents: 5, showWeekends: true },
    configFields: [
      { key: "maxEvents", label: "Max Events to Show", type: "number" },
      { key: "showWeekends", label: "Show Weekends", type: "toggle" },
    ],
  },
  quick_links: {
    type: "quick_links",
    label: "Quick Links",
    description: "Configurable list or grid of quick-access links",
    category: "core",
    icon: "Link2",
    defaultSize: "medium",
    defaultConfig: { display: "grid", hub_key: "" },
    configFields: [
      { key: "display", label: "Display Style", type: "select", options: ["grid", "list"] },
    ],
  },
  announcements: {
    type: "announcements",
    label: "Announcements",
    description: "Latest company announcements and updates",
    category: "core",
    icon: "Megaphone",
    defaultSize: "medium",
    defaultConfig: { maxItems: 3, category: "" },
    configFields: [
      { key: "maxItems", label: "Max Items", type: "number" },
      { key: "category", label: "Filter by Category", type: "text", placeholder: "Leave blank for all" },
    ],
  },
  notifications: {
    type: "notifications",
    label: "Notifications",
    description: "System and hub-level notifications",
    category: "core",
    icon: "Bell",
    defaultSize: "small",
    defaultConfig: { maxItems: 5 },
    configFields: [
      { key: "maxItems", label: "Max Notifications", type: "number" },
    ],
  },
  activity_feed: {
    type: "activity_feed",
    label: "Activity Feed",
    description: "Recent activity across the hub",
    category: "core",
    icon: "Activity",
    defaultSize: "medium",
    defaultConfig: { maxItems: 8, entityFilter: "" },
    configFields: [
      { key: "maxItems", label: "Max Items", type: "number" },
    ],
  },
  kpi: {
    type: "kpi",
    label: "KPI Card",
    description: "Key performance indicator with value and trend",
    category: "core",
    icon: "TrendingUp",
    defaultSize: "small",
    defaultConfig: { metric: "", value: "", unit: "", trend: "", trendDirection: "up", description: "" },
    configFields: [
      { key: "metric", label: "Metric Name", type: "text", placeholder: "e.g. Monthly Revenue" },
      { key: "value", label: "Value", type: "text", placeholder: "e.g. £84,200" },
      { key: "unit", label: "Unit / Label", type: "text", placeholder: "e.g. MTD" },
      { key: "trend", label: "Trend Text", type: "text", placeholder: "e.g. +12% vs last month" },
      { key: "trendDirection", label: "Trend Direction", type: "select", options: ["up", "down", "neutral"] },
      { key: "description", label: "Description", type: "text", placeholder: "Short supporting text" },
    ],
  },
  resource_library: {
    type: "resource_library",
    label: "Resource Library",
    description: "Browse and access documents, guides and files",
    category: "core",
    icon: "BookOpen",
    defaultSize: "medium",
    defaultConfig: { maxItems: 6, category: "" },
    configFields: [
      { key: "maxItems", label: "Max Items", type: "number" },
      { key: "category", label: "Filter Category", type: "text" },
    ],
  },
  powerbi_embed: {
    type: "powerbi_embed",
    label: "Power BI Dashboard",
    description: "Embed a Power BI report or dashboard",
    category: "core",
    icon: "BarChart2",
    defaultSize: "full",
    defaultConfig: { embedUrl: "", height: 500, title: "", showHeader: true },
    configFields: [
      { key: "embedUrl", label: "Power BI Embed URL", type: "text", placeholder: "https://app.powerbi.com/..." },
      { key: "title", label: "Dashboard Title", type: "text" },
      { key: "height", label: "Height (px)", type: "number" },
      { key: "showHeader", label: "Show Header", type: "toggle" },
    ],
  },
  dashboard_embed: {
    type: "dashboard_embed",
    label: "Embed Dashboard",
    description: "Embed any iframe-compatible dashboard (Looker, HubSpot, etc.)",
    category: "core",
    icon: "Monitor",
    defaultSize: "full",
    defaultConfig: { embedUrl: "", embedType: "Custom iframe", height: 460, title: "" },
    configFields: [
      { key: "embedType", label: "Dashboard Type", type: "select", options: ["Power BI", "HubSpot", "Looker Studio", "Custom iframe"] },
      { key: "embedUrl", label: "Embed URL", type: "text", placeholder: "https://..." },
      { key: "title", label: "Title", type: "text" },
      { key: "height", label: "Height (px)", type: "number" },
    ],
  },
  external_launcher: {
    type: "external_launcher",
    label: "System Launcher",
    description: "Quick-launch tiles to external systems and tools",
    category: "core",
    icon: "ExternalLink",
    defaultSize: "medium",
    defaultConfig: { links: [] },
    configFields: [],
  },
  tasks: {
    type: "tasks",
    label: "Tasks",
    description: "Team and personal task list",
    category: "core",
    icon: "CheckSquare",
    defaultSize: "medium",
    defaultConfig: { maxItems: 8, showCompleted: false },
    configFields: [
      { key: "maxItems", label: "Max Tasks", type: "number" },
      { key: "showCompleted", label: "Show Completed", type: "toggle" },
    ],
  },
  ai_assistant: {
    type: "ai_assistant",
    label: "AI Assistant",
    description: "Embedded AI assistant card with quick-prompt shortcuts",
    category: "core",
    icon: "Sparkles",
    defaultSize: "small",
    defaultConfig: { promptSuggestions: ["Help me write a proposal", "Summarise this week's pipeline", "What are our top products?"], title: "AI Assistant" },
    configFields: [
      { key: "title", label: "Widget Title", type: "text" },
    ],
  },

  // ── LEARNING ─────────────────────────────────────────────────────
  my_learning: {
    type: "my_learning",
    label: "My Learning",
    description: "Courses in progress and recently completed",
    category: "learning",
    icon: "GraduationCap",
    defaultSize: "medium",
    defaultConfig: { maxItems: 5 },
    configFields: [{ key: "maxItems", label: "Max Items", type: "number" }],
  },
  assigned_training: {
    type: "assigned_training",
    label: "Assigned Training",
    description: "Training assigned to the current user",
    category: "learning",
    icon: "ClipboardList",
    defaultSize: "medium",
    defaultConfig: { maxItems: 5 },
    configFields: [{ key: "maxItems", label: "Max Items", type: "number" }],
  },
  certificates: {
    type: "certificates",
    label: "Certificates & Badges",
    description: "Earned certifications and achievement badges",
    category: "learning",
    icon: "Award",
    defaultSize: "medium",
    defaultConfig: {},
    configFields: [],
  },
  training_due: {
    type: "training_due",
    label: "Training Due Soon",
    description: "Upcoming training deadlines and expiry alerts",
    category: "learning",
    icon: "AlarmClock",
    defaultSize: "small",
    defaultConfig: { daysAhead: 30 },
    configFields: [{ key: "daysAhead", label: "Days Ahead", type: "number" }],
  },

  // ── SALES ─────────────────────────────────────────────────────────
  sales_pipeline: {
    type: "sales_pipeline",
    label: "Sales Pipeline",
    description: "Pipeline stages and deal values",
    category: "sales",
    icon: "TrendingUp",
    defaultSize: "large",
    defaultConfig: {},
    configFields: [],
  },
  forecast: {
    type: "forecast",
    label: "Forecast",
    description: "Revenue forecast vs target",
    category: "sales",
    icon: "Target",
    defaultSize: "medium",
    defaultConfig: { period: "Monthly" },
    configFields: [{ key: "period", label: "Period", type: "select", options: ["Weekly", "Monthly", "Quarterly"] }],
  },
  top_opportunities: {
    type: "top_opportunities",
    label: "Top Opportunities",
    description: "Highest value open opportunities",
    category: "sales",
    icon: "Star",
    defaultSize: "medium",
    defaultConfig: { maxItems: 5 },
    configFields: [{ key: "maxItems", label: "Max Items", type: "number" }],
  },
  proposal_widget: {
    type: "proposal_widget",
    label: "Proposals",
    description: "Recent proposals and their status",
    category: "sales",
    icon: "FileText",
    defaultSize: "medium",
    defaultConfig: { maxItems: 5 },
    configFields: [{ key: "maxItems", label: "Max Items", type: "number" }],
  },
  leaderboard: {
    type: "leaderboard",
    label: "Leaderboard",
    description: "Top performers ranked by revenue or deals",
    category: "sales",
    icon: "Trophy",
    defaultSize: "medium",
    defaultConfig: { maxItems: 5, metric: "revenue" },
    configFields: [
      { key: "maxItems", label: "Max Rows", type: "number" },
      { key: "metric", label: "Rank By", type: "select", options: ["revenue", "deals", "conversions"] },
    ],
  },
  target_tracker: {
    type: "target_tracker",
    label: "Target Tracker",
    description: "Progress towards monthly or quarterly targets",
    category: "sales",
    icon: "Target",
    defaultSize: "medium",
    defaultConfig: { target: 0, current: 0, period: "Monthly", unit: "£" },
    configFields: [
      { key: "target", label: "Target Value", type: "number" },
      { key: "current", label: "Current Value", type: "number" },
      { key: "period", label: "Period", type: "select", options: ["Weekly", "Monthly", "Quarterly"] },
      { key: "unit", label: "Unit (£, %, deals)", type: "text" },
    ],
  },

  // ── COMPLIANCE ───────────────────────────────────────────────────
  compliance_status: {
    type: "compliance_status",
    label: "Compliance Status",
    description: "Overall compliance health and status summary",
    category: "compliance",
    icon: "ShieldCheck",
    defaultSize: "medium",
    defaultConfig: {},
    configFields: [],
  },
  expiring_certs: {
    type: "expiring_certs",
    label: "Expiring Certifications",
    description: "Certifications expiring in the next 30/60/90 days",
    category: "compliance",
    icon: "AlertTriangle",
    defaultSize: "medium",
    defaultConfig: { daysAhead: 60 },
    configFields: [{ key: "daysAhead", label: "Days Ahead", type: "number" }],
  },
  policy_acknowledgement: {
    type: "policy_acknowledgement",
    label: "Policy Acknowledgements",
    description: "Policies awaiting user acknowledgement",
    category: "compliance",
    icon: "ClipboardCheck",
    defaultSize: "medium",
    defaultConfig: {},
    configFields: [],
  },
  audit_actions: {
    type: "audit_actions",
    label: "Audit Actions",
    description: "Open audit action items and their status",
    category: "compliance",
    icon: "ListChecks",
    defaultSize: "medium",
    defaultConfig: { maxItems: 8 },
    configFields: [{ key: "maxItems", label: "Max Items", type: "number" }],
  },

  // ── OPERATIONS ───────────────────────────────────────────────────
  operational_alerts: {
    type: "operational_alerts",
    label: "Operational Alerts",
    description: "System and operational alerts requiring attention",
    category: "operations",
    icon: "AlertOctagon",
    defaultSize: "medium",
    defaultConfig: { maxItems: 5 },
    configFields: [{ key: "maxItems", label: "Max Items", type: "number" }],
  },
  service_status: {
    type: "service_status",
    label: "Service Status",
    description: "Live status of key services and integrations",
    category: "operations",
    icon: "Activity",
    defaultSize: "medium",
    defaultConfig: {},
    configFields: [],
  },
  workflow_queue: {
    type: "workflow_queue",
    label: "Workflow Queue",
    description: "Items pending in operational workflows",
    category: "operations",
    icon: "GitBranch",
    defaultSize: "medium",
    defaultConfig: { maxItems: 8 },
    configFields: [{ key: "maxItems", label: "Max Items", type: "number" }],
  },
  processing_volumes: {
    type: "processing_volumes",
    label: "Processing Volumes",
    description: "Daily/weekly processing volume metrics",
    category: "operations",
    icon: "BarChart2",
    defaultSize: "medium",
    defaultConfig: { period: "Daily" },
    configFields: [{ key: "period", label: "Period", type: "select", options: ["Daily", "Weekly", "Monthly"] }],
  },

  // ── AI ────────────────────────────────────────────────────────────
  ai_recommended: {
    type: "ai_recommended",
    label: "AI Recommended Resources",
    description: "AI-curated resources based on your role and activity",
    category: "ai",
    icon: "Sparkles",
    defaultSize: "medium",
    defaultConfig: { maxItems: 4 },
    configFields: [{ key: "maxItems", label: "Max Items", type: "number" }],
  },
  ai_suggested_actions: {
    type: "ai_suggested_actions",
    label: "AI Suggested Actions",
    description: "AI-generated next best actions based on your context",
    category: "ai",
    icon: "Wand2",
    defaultSize: "medium",
    defaultConfig: {},
    configFields: [],
  },
  ai_knowledge_search: {
    type: "ai_knowledge_search",
    label: "AI Knowledge Search",
    description: "Semantic search across all knowledge base content",
    category: "ai",
    icon: "Search",
    defaultSize: "medium",
    defaultConfig: { placeholder: "Ask anything…" },
    configFields: [
      { key: "placeholder", label: "Search Placeholder", type: "text" },
    ],
  },
};

// Preconfigured widget templates — ready-to-use starting points
export const WIDGET_TEMPLATES = [
  { id: "kpi_small", label: "Small KPI Card", type: "kpi", size: "small", config: { metric: "Metric", value: "0", unit: "MTD", trend: "", trendDirection: "neutral" } },
  { id: "kpi_large", label: "Large KPI Card", type: "kpi", size: "medium", config: { metric: "Revenue", value: "£0", unit: "Month", trend: "+0% vs last month", trendDirection: "up" } },
  { id: "calendar_agenda", label: "Calendar Agenda", type: "calendar", size: "medium", config: { maxEvents: 5 } },
  { id: "quick_links_list", label: "Quick Links List", type: "quick_links", size: "medium", config: { display: "list" } },
  { id: "quick_links_grid", label: "Quick Links Grid", type: "quick_links", size: "large", config: { display: "grid" } },
  { id: "powerbi_full", label: "Power BI Full Width", type: "powerbi_embed", size: "full", config: { height: 500, showHeader: true } },
  { id: "announcement_list", label: "Announcement List", type: "announcements", size: "medium", config: { maxItems: 3 } },
  { id: "notification_summary", label: "Notification Summary", type: "notifications", size: "small", config: { maxItems: 5 } },
  { id: "resource_list", label: "Resource Library", type: "resource_library", size: "medium", config: { maxItems: 6 } },
  { id: "ai_card", label: "AI Assistant Card", type: "ai_assistant", size: "small", config: {} },
  { id: "leaderboard_table", label: "Leaderboard Table", type: "leaderboard", size: "medium", config: { maxItems: 5, metric: "revenue" } },
  { id: "target_tracker", label: "Target Tracker", type: "target_tracker", size: "medium", config: { period: "Monthly", unit: "£" } },
];

export function getWidgetDef(type) {
  return WIDGET_REGISTRY[type] || null;
}

export function getWidgetsByCategory(category) {
  return Object.values(WIDGET_REGISTRY).filter(w => w.category === category);
}